### ISSUE TITLE
Endpoint: ENOTDIR

### ISSUE THREAD

**Issue by radswiat** [dadi/api#186]
### Expected behavior
Dadi-api should start up with a custom endpoint file in /endpoints directory.

endpointsPath in:
```
Server.prototype.updateEndpoints = function (endpointsPath) {
```
is an file instead of directory path 
( E:\_projects\git\_project\server-dadi\workspace\endpoints\endpoint.test.js )

### Actual behavior

endpointsPath should be a path not a file.

Dadi-api fails to start up with below error:

```
Error: ENOTDIR: not a directory, scandir 'E:\_projects\git\project\server-dadi\workspace\endpoints\endpoint.test.js'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Server.updateEndpoints (E:\_projects\git\_phoenix\server-dadi\node_modules\@dadi\api\dadi\lib\index.js:755:22)
    at E:\_projects\git\_phoenix\server-dadi\node_modules\@dadi\api\dadi\lib\index.js:643:12
    at Array.forEach (native)
    at Server.updateVersions (E:\_projects\git\_phoenix\server-dadi\node_modules\@dadi\api\dadi\lib\index.js:630:12)
    at Server.loadApi (E:\_projects\git\_phoenix\server-dadi\node_modules\@dadi\api\dadi\lib\index.js:274:8)
    at Server.start (E:\_projects\git\_phoenix\server-dadi\node_modules\@dadi\api\dadi\lib\index.js:200:8)
    at Object.<anonymous> (E:\_projects\git\_phoenix\server-dadi\main.js:12:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```
### Quick fix
```js
Server.prototype.updateEndpoints = function (endpointsPath) {
  var self = this
  endpointsPath = path.resolve(process.cwd(), 'workspace/endpoints');
  var endpoints = fs.readdirSync(endpointsPath)
```

### Package details
1.14.2 & 1.15.2
Windows 8 x64

**Comment by eduardoboucas** [comment]
I believe this is because endpoints are meant to be versioned, so API is expecting directories (one per version) under `workspace/endpoints`. In your example, it'd be something like: `E:_projects\git_project\server-dadi\workspace\endpoints\1.0\endpoint.test.js`.

Could you try that and let me know if the issue persists?

Thanks!

**Comment by radswiat** [comment]
That works :) thank you !
