### ISSUE TITLE
Trying to create a new client returns "Cannot find module '../build/Release/bson'"

### ISSUE THREAD

**Issue by victorsferreira** [dadi/api#210]
I've been trying to make the API work, but following the steps in this video 
https://www.youtube.com/channel/UClVQAtFm4DvMTz2YxLmNevA
and in the documentation: http://docs.dadi.tech/api/getting-started/installing/
won't make it work

I get this error:
> Error: Cannot find module '../build/Release/bson'

### Expected behavior
It should show a wizard to create a new client

### Actual behavior
Can't find some module

### Steps to reproduce the problem
Just run 
$ node node_modules/@dadi/api/utils/create-client.js

### Package details
CentOS 7
"@dadi/api": "^1.15.4"
Node 7.7.1
NPM 4.1.2

**Comment by jimlambie** [comment]
Hi @victorsferreira,

I've been working on this recently, and the documentation that goes with it. Could you try the command indicated here: https://github.com/dadi/api/blob/feature/upgrade-mongo-driver/README.md#create-the-first-user

Let me know how that goes, thanks!

**Comment by victorsferreira** [comment]
same thing, Jim

```
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/victorferreira/......../bson/ext/index.js:15:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

```

**Comment by jimlambie** [comment]
Hi @victorsferreira,

I've tried this again, and it does the same for me. However, about a second later, the client record generator starts. I believe it is a warning rather than an error.

Have a look at this thread to see if there's anything that may resolve it for you: http://stackoverflow.com/questions/21656420/failed-to-load-c-bson-extension

```
$  node node_modules/@dadi/api/utils/create-client.js
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jimlambie/api/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{"name":"dadi-api","hostname":"Jamess-MacBook.local","pid":72296,"level":30,"module":"server","msg":"Server logging started.","time":"2017-03-07T22:14:01.935Z","v":0}
Token index: "tokenStore.token_1_tokenExpire_1'
Token expiry index: "tokenStore.created_1', with expireAfterSeconds = 130000

==================================
 DADI API Client Record Generator
==================================

-> Client identifier: (testClient)
```
