### ISSUE TITLE
Possible file storage error issue

### ISSUE THREAD

**Issue by danwdart** [dadi/api#488]
Whilst `/dadi/lib/storage/s3.js` returns a promise on its get() method,
`/dadi/lib/storage/disk.js` may not,
since `serveStatic` doesn't look like it knows about promises.
however they're both created in `/dadi/lib/storage/factory.js`,
which is used in `/dadi/lib/controller/media.js` in `getFile`, and in the static file based routes section in line 519, `.catch` is used - which gave me the following error whilst using file store:

```
/home/dwd/code/commissions/dadi/cloud/api/node_modules/@dadi/api/dadi/lib/controller/media.js:519
      .catch(err => {
      ^

TypeError: Cannot read property 'catch' of undefined
    at Array.server.app.use (/home/dwd/code/commissions/dadi/cloud/api/node_modules/@dadi/api/dadi/lib/controller/media.js:519:7)
    at /home/dwd/code/commissions/dadi/cloud/api/node_modules/@dadi/api/dadi/lib/api/index.js:212:15
    at Array.server.app.use (/home/dwd/code/commissions/dadi/cloud/api/node_modules/@dadi/api/dadi/lib/cache/index.js:59:26)
    at /home/dwd/code/commissions/dadi/cloud/api/node_modules/@dadi/api/dadi/lib/api/index.js:212:15
    at Array.requestLogger (/home/dwd/code/commissions/dadi/cloud/api/node_modules/@dadi/logger/dadi/index.js:229:5)
    at /home/dwd/code/commissions/dadi/cloud/api/node_modules/@dadi/api/dadi/lib/api/index.js:212:15
    at AuthMiddleware.authenticateRequest (/home/dwd/code/commissions/dadi/cloud/api/node_modules/@dadi/api/dadi/lib/auth/index.js:38:12)
    at /home/dwd/code/commissions/dadi/cloud/api/node_modules/@dadi/api/dadi/lib/api/index.js:212:15
    at Array.server.use (/home/dwd/code/commissions/dadi/cloud/api/node_modules/@dadi/api/dadi/lib/controller/featureQueryHandler.js:22:5)
    at /home/dwd/code/commissions/dadi/cloud/api/node_modules/@dadi/api/dadi/lib/api/index.js:212:15
    at Array.<anonymous> (/home/dwd/code/commissions/dadi/cloud/api/node_modules/@dadi/api/dadi/lib/index.js:235:36)
    at /home/dwd/code/commissions/dadi/cloud/api/node_modules/@dadi/api/dadi/lib/api/index.js:212:15
    at Array.server.app.use (/home/dwd/code/commissions/dadi/cloud/api/node_modules/@dadi/api/dadi/lib/cors/index.js:59:5)
    at /home/dwd/code/commissions/dadi/cloud/api/node_modules/@dadi/api/dadi/lib/api/index.js:212:15
    at Array.textParser (/home/dwd/code/commissions/dadi/cloud/api/node_modules/body-parser/lib/types/text.js:69:7)
    at /home/dwd/code/commissions/dadi/cloud/api/node_modules/@dadi/api/dadi/lib/api/index.js:212:15
```
So looks like that ought to have a refactor / always use promises / etc

**Comment by jimlambie** [comment]
@danwdart this is patched in this PR: https://github.com/dadi/api/pull/487

**Comment by danwdart** [comment]
Ah, awesome, just wasn't merged yet, thanks
